# .github/workflows/pr-validate.yml

name: Validate Terraform on PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  validate:
    uses: aisana0131/centralized-workflow/.github/workflows/centralized-workflow.yaml@main
    with:
      terraform-directory: ./terraform
    secrets: inherit