name: Terraform Pipeline test

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Enable debug
        run: set -x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945356073634:role/github-ac-task-terraform-oidc-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      # - name: Terraform Format Check
      #   run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform -chdir="terraform" init

      - name: Terraform Validate
        run: terraform -chdir="terraform" validate

      - name: Terraform Plan
        run: terraform -chdir="terraform" plan -out=tfplan

      - name: Upload plan to S3
        run: aws s3 cp terraform/tfplan s3://ac-task-terraform-state/ec2/tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945356073634:role/github-ac-task-terraform-oidc-role
          aws-region: us-east-1

      - name: Download plan from S3
        run: aws s3 cp s3://ac-task-terraform-state/ec2/tfplan terraform/tfplan

      - name: Terraform Apply
        run: terraform -chdir="terraform" apply -auto-approve tfplan