name: Terraform Pipeline

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Enable debug
        run: set -x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945356073634:role/github-ac-task-terraform-oidc-role
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - run: terraform fmt -check -recursive
      - run: terraform init
        working-directory: ./terraform
      - run: terraform validate
        working-directory: ./terraform
      - run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Upload plan to S3
        working-directory: ./terraform
        run: aws s3 cp tfplan s3://ac-task-terraform-state/ec2/tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945356073634:role/github-ac-task-terraform-oidc-role
          aws-region: us-east-1

      - name: Download plan from S3
        working-directory: ./terraform
        run: aws s3 cp s3://ac-task-terraform-state/ec2/tfplan tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan